### ISSUE TITLE
error[E0522]: definition of an unknown language item: `eh_unwind_resume`

### ISSUE THREAD

**Issue by ghost** [jbaublitz/knock-out#8]
When I compile it, it gives me an error. In this error it also says to run `rustc --explain E0522` for more information about it. When I run the command it explains:
The lang attribute was used in an invalid context.

Erroneous code example:

```
#![feature(lang_items)]

#[lang = "cookie"]
fn cookie() -> ! { // error: definition of an unknown language item: `cookie`
    loop {}
}
```

The lang attribute is intended for marking special items that are built-in to
Rust itself. This includes special traits (like `Copy` and `Sized`) that affect
how the compiler behaves, as well as special functions that may be automatically
invoked (such as the handler for out-of-bounds accesses when indexing a slice).

**Comment by jbaublitz** [comment]
Hi @Yavor-aaa! Can you give a little more detail? I don't use `#[lang = "cookie"]` anywhere in this code base, and I'm unfamiliar with any `"cookie"` language item. See [here](https://doc.rust-lang.org/unstable-book/language-features/lang-items.html) for the list of all supported languages items.

**Comment by jbaublitz** [comment]
@Yavor-aaa I think I understand what your issue was now. I compiled this kernel module again on a more recent version of nightly Rust and it appears that they removed the previously necessary language item `eh_unwind_resume`. I have removed that in commit 059d6bdf3696fe39bdeca206acbc829a52010ac4. I'll close this out.
